// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenuePass.Modules.Events.Infrastructure;

#nullable disable

namespace VenuePass.Modules.Events.Infrastructure.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20260527094659_AddEventAndManifest")]
    partial class AddEventAndManifest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("events")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VenuePass.Modules.Events.Domain.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("event_date");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manifest_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("state");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("events", "events");
                });

            modelBuilder.Entity("VenuePass.Modules.Events.Domain.ManifestTemplates.ManifestTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("manifest_templates", "events");
                });

            modelBuilder.Entity("VenuePass.Modules.Events.Domain.Manifests.Manifest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("bit")
                        .HasColumnName("is_frozen");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("VenueId");

                    b.ToTable("manifests", "events");
                });

            modelBuilder.Entity("VenuePass.Modules.Events.Domain.Venues.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("venues", "events");
                });

            modelBuilder.Entity("VenuePass.Modules.Events.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("LastAttemptedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_attempted_on");

                    b.Property<DateTimeOffset?>("NextAttemptOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("next_attempt_on");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOn")
                        .HasDatabaseName("IX_outbox_messages_occurred_on");

                    b.HasIndex("ProcessedOn", "NextAttemptOn")
                        .HasDatabaseName("IX_outbox_messages_dispatch");

                    b.ToTable("outbox_messages", "events");
                });

            modelBuilder.Entity("VenuePass.Modules.Events.Domain.Events.Event", b =>
                {
                    b.HasOne("VenuePass.Modules.Events.Domain.Venues.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VenuePass.Modules.Events.Domain.ManifestTemplates.ManifestTemplate", b =>
                {
                    b.HasOne("VenuePass.Modules.Events.Domain.Venues.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsMany("VenuePass.Modules.Events.Domain.ManifestTemplates.GeneralAdmissionArea", "GeneralAdmissionAreas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<int>("Capacity")
                                .HasColumnType("int")
                                .HasColumnName("capacity");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name");

                            b1.Property<Guid>("manifest_template_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("manifest_template_id");

                            b1.ToTable("manifest_template_general_admission_areas", "events");

                            b1.WithOwner()
                                .HasForeignKey("manifest_template_id");
                        });

                    b.OwnsMany("VenuePass.Modules.Events.Domain.ManifestTemplates.Section", "Sections", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name");

                            b1.Property<Guid>("manifest_template_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("manifest_template_id");

                            b1.ToTable("manifest_template_sections", "events");

                            b1.WithOwner()
                                .HasForeignKey("manifest_template_id");

                            b1.OwnsMany("VenuePass.Modules.Events.Domain.ManifestTemplates.SeatRow", "Rows", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("id");

                                    b2.Property<string>("Label")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("label");

                                    b2.Property<Guid>("section_id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("section_id");

                                    b2.ToTable("manifest_template_section_rows", "events");

                                    b2.WithOwner()
                                        .HasForeignKey("section_id");

                                    b2.OwnsMany("VenuePass.Modules.Events.Domain.ManifestTemplates.Seat", "Seats", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .HasColumnType("uniqueidentifier")
                                                .HasColumnName("id");

                                            b3.Property<string>("Label")
                                                .IsRequired()
                                                .HasMaxLength(10)
                                                .HasColumnType("nvarchar(10)")
                                                .HasColumnName("label");

                                            b3.Property<Guid>("row_id")
                                                .HasColumnType("uniqueidentifier");

                                            b3.HasKey("Id");

                                            b3.HasIndex("row_id");

                                            b3.ToTable("manifest_template_section_row_seats", "events");

                                            b3.WithOwner()
                                                .HasForeignKey("row_id");
                                        });

                                    b2.Navigation("Seats");
                                });

                            b1.Navigation("Rows");
                        });

                    b.Navigation("GeneralAdmissionAreas");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("VenuePass.Modules.Events.Domain.Manifests.Manifest", b =>
                {
                    b.HasOne("VenuePass.Modules.Events.Domain.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenuePass.Modules.Events.Domain.Venues.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsMany("VenuePass.Modules.Events.Domain.Manifests.GeneralAdmissionArea", "GeneralAdmissionAreas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<int>("Capacity")
                                .HasColumnType("int")
                                .HasColumnName("capacity");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name");

                            b1.Property<Guid>("manifest_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("manifest_id");

                            b1.ToTable("manifest_general_admission_areas", "events");

                            b1.WithOwner()
                                .HasForeignKey("manifest_id");
                        });

                    b.OwnsMany("VenuePass.Modules.Events.Domain.Manifests.Section", "Sections", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name");

                            b1.Property<Guid>("manifest_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("manifest_id");

                            b1.ToTable("manifest_sections", "events");

                            b1.WithOwner()
                                .HasForeignKey("manifest_id");

                            b1.OwnsMany("VenuePass.Modules.Events.Domain.Manifests.SeatRow", "Rows", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("id");

                                    b2.Property<string>("Label")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("label");

                                    b2.Property<Guid>("section_id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("section_id");

                                    b2.ToTable("manifest_section_rows", "events");

                                    b2.WithOwner()
                                        .HasForeignKey("section_id");

                                    b2.OwnsMany("VenuePass.Modules.Events.Domain.Manifests.Seat", "Seats", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .HasColumnType("uniqueidentifier")
                                                .HasColumnName("id");

                                            b3.Property<string>("Label")
                                                .IsRequired()
                                                .HasMaxLength(10)
                                                .HasColumnType("nvarchar(10)")
                                                .HasColumnName("label");

                                            b3.Property<Guid>("row_id")
                                                .HasColumnType("uniqueidentifier");

                                            b3.HasKey("Id");

                                            b3.HasIndex("row_id");

                                            b3.ToTable("manifest_section_row_seats", "events");

                                            b3.WithOwner()
                                                .HasForeignKey("row_id");
                                        });

                                    b2.Navigation("Seats");
                                });

                            b1.Navigation("Rows");
                        });

                    b.Navigation("GeneralAdmissionAreas");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("VenuePass.Modules.Events.Domain.Venues.Venue", b =>
                {
                    b.OwnsOne("VenuePass.Modules.Events.Domain.Venues.VenueAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("VenueId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("country");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("street_address");

                            b1.HasKey("VenueId");

                            b1.ToTable("venues", "events");

                            b1.WithOwner()
                                .HasForeignKey("VenueId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
