// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenuePass.Modules.Attendance.Infrastructure;

#nullable disable

namespace VenuePass.Modules.Attendance.Infrastructure.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    [Migration("20260705042527_AddTicketProjectionRowVersion")]
    partial class AddTicketProjectionRowVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("attendance")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VenuePass.Modules.Attendance.Domain.AttendanceRecords.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CheckedInAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("checked_in_at");

                    b.Property<Guid?>("GeneralAdmissionPoolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("general_admission_pool_id");

                    b.Property<Guid?>("InventorySeatId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_seat_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_item_id");

                    b.Property<Guid>("PublishedEventReferenceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("published_event_reference_id");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nchar(16)")
                        .HasColumnName("ticket_code")
                        .IsFixedLength();

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("TicketCode")
                        .IsUnique()
                        .HasDatabaseName("IX_attendance_records_ticket_code");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("IX_attendance_records_ticket_id");

                    b.HasIndex("PublishedEventReferenceId", "CheckedInAt")
                        .HasDatabaseName("IX_attendance_records_event_checked_in_at");

                    b.ToTable("attendance_records", "attendance", t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceRecords_SeatOrPool", "((inventory_seat_id IS NOT NULL AND general_admission_pool_id IS NULL) OR (inventory_seat_id IS NULL AND general_admission_pool_id IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("VenuePass.Modules.Attendance.Domain.PublishedEvents.PublishedEventReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manifest_id");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "ManifestId")
                        .IsUnique();

                    b.ToTable("published_event_references", "attendance");
                });

            modelBuilder.Entity("VenuePass.Modules.Attendance.Domain.ScanAttempts.ScanAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("NormalizedTicketCode")
                        .HasMaxLength(16)
                        .HasColumnType("nchar(16)")
                        .HasColumnName("normalized_ticket_code")
                        .IsFixedLength();

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("PublishedEventReferenceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("published_event_reference_id");

                    b.Property<string>("RejectionCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("rejection_category");

                    b.Property<DateTimeOffset>("ScannedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("scanned_at");

                    b.Property<string>("SubmittedTicketCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("submitted_ticket_code");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedTicketCode")
                        .HasDatabaseName("IX_scan_attempts_normalized_ticket_code");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_scan_attempts_ticket_id");

                    b.HasIndex("PublishedEventReferenceId", "ScannedAt")
                        .HasDatabaseName("IX_scan_attempts_published_event_reference_id_scanned_at");

                    b.ToTable("scan_attempts", "attendance");
                });

            modelBuilder.Entity("VenuePass.Modules.Attendance.Domain.TicketProjections.TicketProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.Property<Guid?>("GeneralAdmissionPoolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("general_admission_pool_id");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_id");

                    b.Property<Guid?>("InventorySeatId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_seat_id");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_item_id");

                    b.Property<Guid>("PublishedEventReferenceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("published_event_reference_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nchar(16)")
                        .HasColumnName("ticket_code")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK_ticket_projections");

                    b.HasIndex("TicketCode")
                        .IsUnique()
                        .HasDatabaseName("IX_ticket_projections_ticket_code");

                    b.HasIndex("PublishedEventReferenceId", "Status")
                        .HasDatabaseName("IX_ticket_projections_published_event_reference_id_status");

                    b.ToTable("ticket_projections", "attendance", t =>
                        {
                            t.HasCheckConstraint("CK_ticket_projections_seat_or_pool", "((inventory_seat_id IS NOT NULL AND general_admission_pool_id IS NULL) OR (inventory_seat_id IS NULL AND general_admission_pool_id IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("VenuePass.Modules.Attendance.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("LastAttemptedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_attempted_on");

                    b.Property<DateTimeOffset?>("NextAttemptOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("next_attempt_on");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOn")
                        .HasDatabaseName("IX_outbox_messages_occurred_on");

                    b.HasIndex("ProcessedOn", "NextAttemptOn")
                        .HasDatabaseName("IX_outbox_messages_dispatch");

                    b.ToTable("outbox_messages", "attendance");
                });

            modelBuilder.Entity("VenuePass.Modules.Attendance.Domain.AttendanceRecords.AttendanceRecord", b =>
                {
                    b.HasOne("VenuePass.Modules.Attendance.Domain.PublishedEvents.PublishedEventReference", null)
                        .WithMany()
                        .HasForeignKey("PublishedEventReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VenuePass.Modules.Attendance.Domain.ScanAttempts.ScanAttempt", b =>
                {
                    b.HasOne("VenuePass.Modules.Attendance.Domain.PublishedEvents.PublishedEventReference", null)
                        .WithMany()
                        .HasForeignKey("PublishedEventReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VenuePass.Modules.Attendance.Domain.TicketProjections.TicketProjection", b =>
                {
                    b.HasOne("VenuePass.Modules.Attendance.Domain.PublishedEvents.PublishedEventReference", null)
                        .WithMany()
                        .HasForeignKey("PublishedEventReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
