// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenuePass.Modules.Attendance.Infrastructure;

#nullable disable

namespace VenuePass.Modules.Attendance.Infrastructure.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    [Migration("20260627082540_AddOutbox")]
    partial class AddOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("attendance")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VenuePass.Modules.Attendance.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("LastAttemptedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_attempted_on");

                    b.Property<DateTimeOffset?>("NextAttemptOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("next_attempt_on");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOn")
                        .HasDatabaseName("IX_outbox_messages_occurred_on");

                    b.HasIndex("ProcessedOn", "NextAttemptOn")
                        .HasDatabaseName("IX_outbox_messages_dispatch");

                    b.ToTable("outbox_messages", "attendance");
                });
#pragma warning restore 612, 618
        }
    }
}
