// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenuePass.Modules.Ticketing.Infrastructure;

#nullable disable

namespace VenuePass.Modules.Ticketing.Infrastructure.Migrations
{
    [DbContext(typeof(TicketingDbContext))]
    [Migration("20260608093039_UpdateTicketing")]
    partial class UpdateTicketing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ticketing")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VenuePass.Modules.Ticketing.Domain.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("EventReferenceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_reference_id");

                    b.HasKey("Id");

                    b.HasIndex("EventReferenceId")
                        .IsUnique();

                    b.ToTable("inventories", "ticketing");
                });

            modelBuilder.Entity("VenuePass.Modules.Ticketing.Domain.PublishedEvents.PublishedEventReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manifest_id");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("published_event_references", "ticketing");
                });

            modelBuilder.Entity("VenuePass.Modules.Ticketing.Domain.Inventories.Inventory", b =>
                {
                    b.HasOne("VenuePass.Modules.Ticketing.Domain.PublishedEvents.PublishedEventReference", null)
                        .WithOne()
                        .HasForeignKey("VenuePass.Modules.Ticketing.Domain.Inventories.Inventory", "EventReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("VenuePass.Modules.Ticketing.Domain.Inventories.GeneralAdmissionPool", "Pools", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<int>("AvailableCount")
                                .HasColumnType("int")
                                .HasColumnName("available_count");

                            b1.Property<int>("Capacity")
                                .HasColumnType("int")
                                .HasColumnName("capacity");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name");

                            b1.Property<Guid>("SourceAreaId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("source_area_id");

                            b1.Property<Guid>("inventory_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("inventory_id");

                            b1.ToTable("inventory_pools", "ticketing");

                            b1.WithOwner()
                                .HasForeignKey("inventory_id");
                        });

                    b.OwnsMany("VenuePass.Modules.Ticketing.Domain.Inventories.InventorySeat", "Seats", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("Availability")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("availability");

                            b1.Property<string>("Row")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("row");

                            b1.Property<string>("Seat")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("seat");

                            b1.Property<string>("Section")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("section");

                            b1.Property<Guid>("SourceSeatId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("source_seat_id");

                            b1.Property<Guid>("inventory_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("inventory_id");

                            b1.ToTable("inventory_seats", "ticketing");

                            b1.WithOwner()
                                .HasForeignKey("inventory_id");
                        });

                    b.Navigation("Pools");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
