// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenuePass.Modules.Ticketing.Infrastructure;

#nullable disable

namespace VenuePass.Modules.Ticketing.Infrastructure.Migrations
{
    [DbContext(typeof(TicketingDbContext))]
    [Migration("20260612101659_AddReservations")]
    partial class AddReservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ticketing")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VenuePass.Modules.Ticketing.Domain.Inventories.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("EventReferenceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_reference_id");

                    b.HasKey("Id");

                    b.HasIndex("EventReferenceId")
                        .IsUnique();

                    b.ToTable("inventories", "ticketing");
                });

            modelBuilder.Entity("VenuePass.Modules.Ticketing.Domain.Offers.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SalesRange", "VenuePass.Modules.Ticketing.Domain.Offers.Offer.SalesRange#DateTimeRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("sales_end");

                            b1.Property<DateTimeOffset?>("Start")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("sales_start");
                        });

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("offers", "ticketing");
                });

            modelBuilder.Entity("VenuePass.Modules.Ticketing.Domain.PublishedEvents.PublishedEventReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manifest_id");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("published_event_references", "ticketing");
                });

            modelBuilder.Entity("VenuePass.Modules.Ticketing.Domain.Reservations.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_id");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("offer_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("OfferId");

                    b.ToTable("reservations", "ticketing");
                });

            modelBuilder.Entity("VenuePass.Modules.Ticketing.Domain.Inventories.Inventory", b =>
                {
                    b.HasOne("VenuePass.Modules.Ticketing.Domain.PublishedEvents.PublishedEventReference", null)
                        .WithOne()
                        .HasForeignKey("VenuePass.Modules.Ticketing.Domain.Inventories.Inventory", "EventReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("VenuePass.Modules.Ticketing.Domain.Inventories.GeneralAdmissionPool", "Pools", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<int>("Capacity")
                                .HasColumnType("int")
                                .HasColumnName("capacity");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name");

                            b1.Property<int>("ReservedCount")
                                .HasColumnType("int")
                                .HasColumnName("reserved_count");

                            b1.Property<byte[]>("RowVersion")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("rowversion")
                                .HasColumnName("row_version");

                            b1.Property<int>("SoldCount")
                                .HasColumnType("int")
                                .HasColumnName("sold_count");

                            b1.Property<Guid>("SourceAreaId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("source_area_id");

                            b1.Property<Guid>("inventory_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("inventory_id");

                            b1.ToTable("inventory_pools", "ticketing");

                            b1.WithOwner()
                                .HasForeignKey("inventory_id");
                        });

                    b.OwnsMany("VenuePass.Modules.Ticketing.Domain.Inventories.InventorySeat", "Seats", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("Availability")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("availability");

                            b1.Property<string>("Row")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("row");

                            b1.Property<byte[]>("RowVersion")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("rowversion")
                                .HasColumnName("row_version");

                            b1.Property<string>("Seat")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("seat");

                            b1.Property<string>("Section")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("section");

                            b1.Property<Guid>("SourceSeatId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("source_seat_id");

                            b1.Property<Guid>("inventory_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("inventory_id");

                            b1.ToTable("inventory_seats", "ticketing");

                            b1.WithOwner()
                                .HasForeignKey("inventory_id");
                        });

                    b.Navigation("Pools");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("VenuePass.Modules.Ticketing.Domain.Offers.Offer", b =>
                {
                    b.HasOne("VenuePass.Modules.Ticketing.Domain.Inventories.Inventory", null)
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("VenuePass.Modules.Ticketing.Domain.Offers.PriceZone", "PriceZones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name");

                            b1.Property<decimal>("Price")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("price");

                            b1.Property<Guid>("offer_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("offer_id", "Name")
                                .IsUnique()
                                .HasDatabaseName("ux_offer_price_zones_offer_id_name");

                            b1.ToTable("offer_price_zones", "ticketing");

                            b1.WithOwner()
                                .HasForeignKey("offer_id");

                            b1.OwnsMany("VenuePass.Modules.Ticketing.Domain.Offers.PriceZoneGeneralAdmissionPoolItem", "GeneralAdmissionPoolItems", b2 =>
                                {
                                    b2.Property<Guid>("price_zone_id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("GeneralAdmissionPoolId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("general_admission_pool_id");

                                    b2.HasKey("price_zone_id", "GeneralAdmissionPoolId");

                                    b2.HasIndex("GeneralAdmissionPoolId");

                                    b2.ToTable("offer_price_zone_general_admission_pool_items", "ticketing");

                                    b2.WithOwner()
                                        .HasForeignKey("price_zone_id");
                                });

                            b1.OwnsMany("VenuePass.Modules.Ticketing.Domain.Offers.PriceZoneInventorySeatItem", "InventorySeatItems", b2 =>
                                {
                                    b2.Property<Guid>("price_zone_id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("InventorySeatId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("inventory_seat_id");

                                    b2.HasKey("price_zone_id", "InventorySeatId");

                                    b2.HasIndex("InventorySeatId");

                                    b2.ToTable("offer_price_zone_inventory_seat_items", "ticketing");

                                    b2.WithOwner()
                                        .HasForeignKey("price_zone_id");
                                });

                            b1.Navigation("GeneralAdmissionPoolItems");

                            b1.Navigation("InventorySeatItems");
                        });

                    b.Navigation("PriceZones");
                });

            modelBuilder.Entity("VenuePass.Modules.Ticketing.Domain.Reservations.Reservation", b =>
                {
                    b.HasOne("VenuePass.Modules.Ticketing.Domain.Inventories.Inventory", null)
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VenuePass.Modules.Ticketing.Domain.Offers.Offer", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("VenuePass.Modules.Ticketing.Domain.Reservations.ReservationItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<Guid?>("GeneralAdmissionPoolId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("general_admission_pool_id");

                            b1.Property<Guid?>("InventorySeatId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("inventory_seat_id");

                            b1.Property<Guid>("PriceZoneId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("price_zone_id");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("quantity");

                            b1.Property<decimal>("Total")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("total");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("type");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("unit_price");

                            b1.Property<Guid>("reservation_id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("reservation_id");

                            b1.ToTable("reservation_items", "ticketing");

                            b1.WithOwner()
                                .HasForeignKey("reservation_id");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
