// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenuePass.Modules.Ticketing.Infrastructure;

#nullable disable

namespace VenuePass.Modules.Ticketing.Infrastructure.Migrations
{
    [DbContext(typeof(TicketingDbContext))]
    partial class TicketingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ticketing")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VenuePass.Modules.Ticketing.Domain.PublishedEvents.PublishedEventReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manifest_id");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.ToTable("published_event_references", "ticketing");
                });
#pragma warning restore 612, 618
        }
    }
}
